[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "numpy>=2.3.4",
  "pandas",
]

[dependency-groups]
dev = [
    "pylyzer>=0.0.82",
    "pyright>=1.1.406",
    "ruff>=0.14.1",
]
